import { Metadata } from "next"

export const metadata: Metadata  = {
    title: 'Next.js',
    description: 'Generated by Next.js',
  }
  
  function getRandomInt(max: number) {
    return Math.floor(Math.random() * max);
}
  export default function ProductDetailsLayout({
    children,
  }: {
    children: React.ReactNode
  }) {
    const random = getRandomInt(2)
    if (random ===1){
      throw new Error("Error loading product")
  }
    return (
          <>
          {children}
          <h2>Featured products</h2>
          </>
    )
}